#!/bin/bash
cat /etc/passwd
cat /etc/passwd /etc/hosts
cat /etc/passwd /etc/hosts
cat /etc/passwd /etc/hosts
cat /etc/passwd /etc/hosts
cat /etc/passwd /etc/hosts
tail -n 10 /etc/passwd
tail -n 10 /etc/passwd
